The bluetooth module build falls over with the following compiler error.
  BluetoothSocketAddress.cpp: In member function 'void BluetoothSocketAddress::set_address(const string&)':
  BluetoothSocketAddress.cpp:151:61: error: taking address of temporary [-fpermissive]
  BluetoothSocketAddress.cpp:156:61: error: taking address of temporary [-fpermissive]

This was initially reported by the Buildroot autobuilder, here:

  http://autobuild.buildroot.net/results/d1133da3f8d74c58fd271e0cab197a1108000e90/build-end.log

The underlying problem is with the definition of BDADDR_ANY in the
bluetooth.h header; this definition necessarily invlolves taking the address
of a temporary, which is unacceptable to g++.

There are two obvious solutions:

* Squash the compile error using -fpermissive
* Provide a local variable equivalent to BDADDR_ANY, to use in its place

Neither solution is perfect: the first seems somewhat worse, in that it will
also mask other, unrelated compilation problems.

Further details can be found here:

  http://stackoverflow.com/questions/9751710/c-c-warning-address-of-temporary-with-bdaddr-any-bluetooth-library